version: '3.8'
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args:
        - NODE_ENV:development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev


  mongo:
    environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example